# Generated by Django 3.0.1 on 2019-12-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('time_posted', models.DateTimeField()),
                ('url', models.URLField()),
                ('vector', models.CharField(max_length=2048)),
                ('text', models.CharField(max_length=4096)),
            ],
        ),
    ]
