# Generated by Django 3.0.3 on 2020-02-14 01:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=64)),
                ('company', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=8)),
                ('country', models.CharField(blank=True, max_length=16)),
                ('source', models.CharField(blank=True, max_length=16)),
                ('date_posted', models.DateField(default=datetime.date.today)),
                ('url', models.URLField(blank=True)),
                ('vector', models.BinaryField()),
                ('description', models.CharField(blank=True, max_length=256)),
                ('image_url', models.URLField(blank=True)),
                ('search_title', models.CharField(blank=True, max_length=16)),
                ('num_employees', models.IntegerField(null=True)),
            ],
        ),
    ]
