# Generated by Django 3.0.1 on 2019-12-31 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='text',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='time_posted',
        ),
        migrations.AddField(
            model_name='posting',
            name='company',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='posting',
            name='date_posted',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='posting',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='posting',
            name='location',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='posting',
            name='source',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='posting',
            name='title',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='posting',
            name='vector',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
