# Generated by Django 3.0.1 on 2019-12-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_auto_20191231_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
