# Generated by Django 3.0.1 on 2020-01-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_auto_20191231_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='id',
            field=models.CharField(editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
