# Generated by Django 3.0.1 on 2019-12-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vector',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
