# Generated by Django 3.0.1 on 2020-01-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_education_major'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='major',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='institution',
            new_name='school_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vector',
        ),
        migrations.AddField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='education',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
