# Generated by Django 3.0.1 on 2020-01-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200110_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='title',
            field=models.CharField(default='', max_length=32),
        ),
    ]
