# Generated by Django 3.0.1 on 2020-01-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20200112_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(default=''),
        ),
    ]
