# Generated by Django 3.0.3 on 2020-02-14 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postings', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerUser',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=32)),
                ('last_name', models.CharField(blank=True, max_length=32)),
                ('desired_location', models.CharField(blank=True, max_length=32)),
                ('desired_title', models.CharField(blank=True, max_length=64)),
                ('profile_pic_url', models.CharField(blank=True, max_length=256)),
                ('gender', models.CharField(blank=True, max_length=16)),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
                ('saved_postings', models.ManyToManyField(to='postings.Posting')),
            ],
        ),
    ]
