# Generated by Django 3.0.1 on 2020-01-15 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0008_auto_20200112_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerUser',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('desired_location', models.CharField(blank=True, max_length=32)),
                ('desired_title', models.CharField(blank=True, max_length=64)),
                ('profil_pic_url', models.CharField(blank=True, max_length=256)),
                ('gender', models.CharField(blank=True, max_length=16)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
