# Generated by Django 3.0.1 on 2020-01-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_users', '0002_auto_20200115_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messengeruser',
            name='user',
        ),
    ]
