# Generated by Django 3.0.3 on 2020-03-18 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200214_0111'),
        ('messenger_users', '0002_messengeruser_clicked_postings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messengeruser',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Profile'),
        ),
    ]
