# Generated by Django 3.0.1 on 2020-01-15 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20200112_1918'),
        ('messenger_users', '0003_remove_messengeruser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messengeruser',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
    ]
