# Generated by Django 3.0.1 on 2020-01-15 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_users', '0004_auto_20200115_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messengeruser',
            old_name='profil_pic_url',
            new_name='profile_pic_url',
        ),
    ]
