# Generated by Django 3.0.1 on 2020-01-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_users', '0005_auto_20200115_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengeruser',
            name='first_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='messengeruser',
            name='last_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
