# Generated by Django 3.0.1 on 2020-01-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_users', '0006_auto_20200117_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messengeruser',
            name='id',
            field=models.CharField(editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
